#!/bin/bash  

######################################################
# INSTANT INSTALASI WEBSERVER APACHE MYSQL PHPMYADMIN#
# RYUGEN XD                                          #
#####################################################

DIR="/sdcard/htdocs"
PACKAGE_NAME="zhell server"

termux-setup-storage
printf "\033[1;33m upgrade APT\033[0m\n";
apt upgrade;
printf "\033[1;33m update APT\033[0m\n";
apt update;
printf "\033[1;33m update package termux\033[0m\n";
pkg update;
printf "\033[1;33m upgrade package termux\033[0m\n";
pkg upgrade;
pkg install figlet
figlet $PACKAGE_NAME

# check if folder not exist
if [ ! -d "$DIR" ]; then
  mkdir $DIR
fi

sh bin/install.sh
