#!/bin/bash  
######################################################
# INSTANT INSTALASI WEBSERVER APACHE MYSQL PHPMYADMIN#
# RYUGEN XD                                          #
#####################################################
pkg install figlet;
figlet zhell Server;
sh bin/install.sh;